### PR TITLE
Add missing telemetry callback

### PR DESCRIPTION
**Pull request by markus-franke**
Taken from

https://www.qt.io/blog/option-to-provide-anonymous-usage-statistics-enabled

### CODE REVIEW

**Comment by markus-franke** [comment]
I have no idea why the CI fails. Any comments on this?

**Comment by skalee** [comment]
Thanks a lot for your fix!

It is all good, and the build failure has happened due to some glitch in Travis CI. Restarting it did help. Having said that, I preferred to write it once again in order to keep the code style consistent with the rest of the script. Hence, I'm closing it in favour of #5.

Sorry for late response.

**Comment by markus-franke** [comment]
> Thanks a lot for your fix!
> 
> It is all good, and the build failure has happened due to some glitch in Travis CI. Restarting it did help. Having said that, I preferred to write it once again in order to keep the code style consistent with the rest of the script. Hence, I'm closing it in favour of #5.
> 
> Sorry for late response.

Thanks for fixing that and sure - your solution probably better fit's the style of your project. I simply copy-pasted my solution from the Qt page and at least it worked for me as a quick fix. :-)

**Comment by skalee** [comment]
It's just a matter of consistent style. They are equivalent in other aspects.

**Pull request closed without merging**
